### ISSUE TITLE
Prompt command to disable the extruder heating?

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#21]

**Comment by donovan6000** [comment]
Using MatterControl's calibration procedures with iMe probably isn't a good idea. MatterControl's calibration is designed for RepRap firmwares like Marlin and Sprinter. iMe uses RepRap's protocol to send/receive data, but it isn't a RepRap firmware since it only implements the G-code commands used in M3D's firmwares.

iMe has builtin bed leveling that MatterControl doesn't know how to adjust, so trying to calibrate the printer with MatterControl will probably result in some unexpected behaviors. M3D Fio is the only program that can correctly calibrate the printer when it's using iMe.

**Comment by qwerty8224** [comment]
Thank you
