### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#37]
You can add a change CALIBRATE_Z0_CORRECTION?

**Comment by donovan6000** [comment]
I'll add it into the next version of iMe.

**Comment by qwerty8224** [comment]
Thanks I think many like it.

**Comment by donovan6000** [comment]
Newest [devel version](https://github.com/donovan6000/iMe/tree/devel) allows setting the calibrate Z0 correction. Positive values mean higher up, and negative values mean lower down. So a calibrate Z0 correction of +2.7mm means to move the Z0 up by 2.7mm higher than it sensed it to be.

**Comment by dieideeistgut** [comment]
Hello - sorry to re-open. Found that you can't set the Z0 correction to a negative number because "min" html-attribute on the field itself is set to a positive number. Removing this (via Devtools, or such) lets me set negative values though. Just wanted to drop this note and leave a 👍 for all the work that has been done here.

**Comment by donovan6000** [comment]
@dieideeistgut Thanks. It's fixed in [M33 Fio's devel version](https://github.com/donovan6000/M33-Fio/tree/devel) now.
